name: "immich-public-proxy"
services:
  immich-public-proxy:
    image: "11notes/immich-public-proxy:1.3.3"
    container_name: "immich-public-proxy"
    environment:
      TZ: "Europe/Zurich"
      IMMICH_PUBLIC_PROXY_PUBLIC_URL: "https://photos.domain.com"
      IMMICH_PUBLIC_PROXY_LIGHT_GALLERY_CONFIG: |-
        {
          "lightGallery": {
            "controls": true,
            "download": false,
            "mobileSettings": {
              "controls": false,
              "showCloseIcon": true,
              "download": false
            }
          }
        }
    ports:
      - "3000:3000/tcp"
    restart: "always"